
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.models.Producto;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_USER
 */
public class BuscarProductoView extends javax.swing.JInternalFrame {
    
    
    public BuscarProductoView() {
        initComponents();  
        
    }

    public JButton getBtnAceptarBs() {
        return btnAceptarBs;
    }

    public void setBtnAceptarBs(JButton btnAceptarBs) {
        this.btnAceptarBs = btnAceptarBs;
    }

    public JButton getBtnCancelarBs() {
        return btnCancelarBs;
    }

    public void setBtnCancelarBs(JButton btnCancelarBs) {
        this.btnCancelarBs = btnCancelarBs;
    }
    public JTextField getLbCodigoBs() {
        return lbCodigoBs;
    }

    public void setLbCodigoBs(JTextField lbCodigoBs) {
        this.lbCodigoBs = lbCodigoBs;
    }

    public JTextField getTxtMostrarNombre() {
        return TxtMostrarNombre;
    }

    public void setTxtMostrarNombreBuscar(JTextField TxtMostrarNombre) {
        this.TxtMostrarNombre = TxtMostrarNombre;
    }

    public JTextField getTxtMostrarPrecio() {
        return TxtMostrarPrecio;
    }

    public void setTxtMostrarPrecio(JTextField TxtMostrarPrecio) {
        this.TxtMostrarPrecio = TxtMostrarPrecio;
    }
    
    public void mostrarProducto(Producto producto){
        TxtMostrarNombre.setText(producto.getNombre());
        TxtMostrarPrecio.setText(String.valueOf(producto.getPrecio()));
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JLabel();
        lbCodigoBs = new javax.swing.JTextField();
        btnAceptarBs = new javax.swing.JButton();
        btnCancelarBs = new javax.swing.JButton();
        TxtMostrarNombre = new javax.swing.JTextField();
        txtCodigo1 = new javax.swing.JLabel();
        TxtMostrarPrecio = new javax.swing.JTextField();
        txtCodigo2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Producto");

        txtCodigo.setText("Ingrese codigo :");

        lbCodigoBs.addActionListener(this::lbCodigoBsActionPerformed);

        btnAceptarBs.setText("Aceptar");
        btnAceptarBs.addActionListener(this::btnAceptarBsActionPerformed);

        btnCancelarBs.setText("Cancelar");
        btnCancelarBs.addActionListener(this::btnCancelarBsActionPerformed);

        TxtMostrarNombre.addActionListener(this::TxtMostrarNombreActionPerformed);

        txtCodigo1.setText("Ingrese precio a buscar :");

        TxtMostrarPrecio.addActionListener(this::TxtMostrarPrecioActionPerformed);

        txtCodigo2.setText("Ingrese nombre :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnAceptarBs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarBs))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMostrarPrecio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigoBs, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtMostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo)
                    .addComponent(lbCodigoBs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo2)
                    .addComponent(TxtMostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo1)
                    .addComponent(TxtMostrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarBs)
                    .addComponent(btnCancelarBs))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCodigoBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbCodigoBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbCodigoBsActionPerformed

    private void btnAceptarBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarBsActionPerformed

    private void btnCancelarBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBsActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarBsActionPerformed

    private void TxtMostrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMostrarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMostrarNombreActionPerformed

    private void TxtMostrarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMostrarPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMostrarPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMostrarNombre;
    private javax.swing.JTextField TxtMostrarPrecio;
    private javax.swing.JButton btnAceptarBs;
    private javax.swing.JButton btnCancelarBs;
    private javax.swing.JTextField lbCodigoBs;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtCodigo1;
    private javax.swing.JLabel txtCodigo2;
    // End of variables declaration//GEN-END:variables

    public void mostrarProductoBuscar(Producto p) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}