
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.models.Producto;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_USER
 */
public class BuscarProductoView extends javax.swing.JInternalFrame {
    
    
    public BuscarProductoView() {
        initComponents();  
        
    }

    public JButton getBtnAceptarBs() {
        return btnAceptarBs;
    }

    public void setBtnAceptarBs(JButton btnAceptarBs) {
        this.btnAceptarBs = btnAceptarBs;
    }

    public JButton getBtnCancelarBs() {
        return btnCancelarBs;
    }

    public void setBtnCancelarBs(JButton btnCancelarBs) {
        this.btnCancelarBs = btnCancelarBs;
    }
    public JTextField getLbCodigoBs() {
        return lbCodigoBs;
    }

    public void setLbCodigoBs(JTextField lbCodigoBs) {
        this.lbCodigoBs = lbCodigoBs;
    }
    
    public void mostrarProducto(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
        dispose(); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JLabel();
        lbCodigoBs = new javax.swing.JTextField();
        btnAceptarBs = new javax.swing.JButton();
        btnCancelarBs = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Producto");

        txtCodigo.setText("Ingrese codigo :");

        lbCodigoBs.addActionListener(this::lbCodigoBsActionPerformed);

        btnAceptarBs.setText("Aceptar");
        btnAceptarBs.addActionListener(this::btnAceptarBsActionPerformed);

        btnCancelarBs.setText("Cancelar");
        btnCancelarBs.addActionListener(this::btnCancelarBsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCodigoBs, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnAceptarBs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarBs)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCodigoBs)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarBs)
                    .addComponent(btnCancelarBs))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCodigoBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbCodigoBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbCodigoBsActionPerformed

    private void btnAceptarBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarBsActionPerformed

    private void btnCancelarBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBsActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarBsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarBs;
    private javax.swing.JButton btnCancelarBs;
    private javax.swing.JTextField lbCodigoBs;
    private javax.swing.JLabel txtCodigo;
    // End of variables declaration//GEN-END:variables

    public void mostrarProductoBuscar(Producto p) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}