/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.controllers.ProductoController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_USER
 */
public class BuscarProductoView extends javax.swing.JInternalFrame {
    private ProductoController productoControllerView;
    public BuscarProductoView() {
        initComponents();  
        this.productoControllerView = productoControllerView;
    }

    public JButton getBtnAceptarBs() {
        return btnAceptarBs;
    }

    public void setBtnAceptarBs(JButton btnAceptarBs) {
        this.btnAceptarBs = btnAceptarBs;
    }

    public JButton getBtnCancelarBs() {
        return btnCancelarBs;
    }

    public void setBtnCancelarBs(JButton btnCancelarBs) {
        this.btnCancelarBs = btnCancelarBs;
    }

    public JTextField getLbCodigoBs() {
        return lbCodigoBs;
    }

    public void setLbCodigoBs(JTextField lbCodigoBs) {
        this.lbCodigoBs = lbCodigoBs;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JLabel();
        lbCodigoBs = new javax.swing.JTextField();
        btnAceptarBs = new javax.swing.JButton();
        btnCancelarBs = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txtCodigo.setText("Ingrese codigo:");

        lbCodigoBs.addActionListener(this::lbCodigoBsActionPerformed);

        btnAceptarBs.setText("Aceptar");
        btnAceptarBs.addActionListener(this::btnAceptarBsActionPerformed);

        btnCancelarBs.setText("Cancelar");
        btnCancelarBs.addActionListener(this::btnCancelarBsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCodigoBs, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnAceptarBs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarBs)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigoBs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBs)
                    .addComponent(btnAceptarBs))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        btnAceptarBs.getAccessibleContext().setAccessibleName("Aceptar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCodigoBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbCodigoBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbCodigoBsActionPerformed

    private void btnAceptarBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarBsActionPerformed

    private void btnCancelarBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBsActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarBsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarBs;
    private javax.swing.JButton btnCancelarBs;
    private javax.swing.JTextField lbCodigoBs;
    private javax.swing.JLabel txtCodigo;
    // End of variables declaration//GEN-END:variables
}
