
package ec.edu.ups.carrito.views;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_USER
 */
public class CrearProductoView extends javax.swing.JInternalFrame {
    /**
     * Creates new form CrearProductoView
     */
    public CrearProductoView() {
        initComponents();
    }

    public JButton getBntAceptar() {
        return bntAceptar;
    }

    public void setBntAceptar(JButton bntAceptar) {
        this.bntAceptar = bntAceptar;
    }

    public JButton getBntCancelar() {
        return bntCancelar;
    }

    public void setBntCancelar(JButton bntCancelar) {
        this.bntCancelar = bntCancelar;
    
    }
    public void mostrarInformacion(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje);
    }

    public JTextField getTxtCodigo() {
        return txtCrearCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCrearCodigo = txtCodigo;
    }

    public JTextField getTxtCrearCodigo() {
        return txtCrearCodigo;
    }

    public void setTxtCrearCodigo(JTextField txtCrearCodigo) {
        this.txtCrearCodigo = txtCrearCodigo;
    }

    public JTextField getTxtCrearNombre() {
        return txtCrearNombre;
    }

    public void setTxtCrearNombre(JTextField txtCrearNombre) {
        this.txtCrearNombre = txtCrearNombre;
    }

    public JTextField getTxtCrearPrecio() {
        return txtCrearPrecio;
    }

    public void setTxtCrearPrecio(JTextField txtCrearPrecio) {
        this.txtCrearPrecio = txtCrearPrecio;
    }

    
    
    public void mostrarProducto(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
        dispose(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCrearCodigo = new javax.swing.JTextField();
        bntAceptar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        txtCrearNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCrearPrecio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Producto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel1.setText("Codigo");

        txtCrearCodigo.addActionListener(this::txtCrearCodigoActionPerformed);

        bntAceptar.setText("Aceptar");
        bntAceptar.addActionListener(this::bntAceptarActionPerformed);

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(this::bntCancelarActionPerformed);

        txtCrearNombre.addActionListener(this::txtCrearNombreActionPerformed);

        jLabel2.setText("Precio:");

        jLabel3.setText("Nombre:");

        txtCrearPrecio.addActionListener(this::txtCrearPrecioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(bntAceptar)
                .addGap(18, 18, 18)
                .addComponent(bntCancelar)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCrearNombre)
                    .addComponent(txtCrearCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(txtCrearPrecio))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCrearCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrearNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCrearPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCancelar)
                    .addComponent(bntAceptar))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCrearCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearCodigoActionPerformed

    private void bntAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAceptarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void txtCrearNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearNombreActionPerformed

    private void txtCrearPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAceptar;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCrearCodigo;
    private javax.swing.JTextField txtCrearNombre;
    private javax.swing.JTextField txtCrearPrecio;
    // End of variables declaration//GEN-END:variables

    public Object getTxtNombre() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getTxtPrecio() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
